# Generated by Django 3.1.4 on 2020-12-27 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Diary',
            },
        ),
    ]
